### ISSUE TITLE
Svg version for v3 version

### ISSUE THREAD

**Issue by yangwao** [kodadot/kodadot-presskit#15]
We should add SVG version

https://github.com/kodadot/kodadot-presskit/pull/11#issuecomment-963969280

**Comment by roiLeo** [comment]
SVG version for V3

**Comment by yangwao** [comment]
> SVG version for V3:
> 
> * logo K.

where 👀 you maybe wanted open PR?

**Comment by roiLeo** [comment]
> where 👀 you maybe wanted open PR?

I can't export "K." icon smaller size from figma in .svg every time I try It comes out stretched.
Maybe we can try to export it from illustrator?

**Comment by yangwao** [comment]
@XyloDrone may can help on this!

**Comment by XyloDrone** [comment]
Where is the logo going? I'll export or link the right version.

**Comment by roiLeo** [comment]
> Where is the logo going? I'll export or link the right version.

I think the logo is going in navbar in https://github.com/kodadot/nft-gallery/pull/1274.
I added a comment in the figma file to know which one to export.

**Comment by XyloDrone** [comment]
Alright, give this one a shot, I also added the "beta" label sign to it.
[Koda_Beta_Nav.svg.zip](https://github.com/kodadot/kodadot-presskit/files/7780456/Koda_Beta_Nav.svg.zip)
Would appreciate it if you could send over a screenshot so I can see how it looks.

**Comment by XyloDrone** [comment]
I have designed a new nav bar and will upload this soon, would you like to give me a couple of hours until I finish up the desgin of the new gallery?
