### ISSUE TITLE
Wen v3

### ISSUE THREAD

**Issue by vikiival** [kodadot/kodadot-presskit#16]
> I notice that Kodadot have other logo can you share with us , our partnership video is almost ready so we need it

**Comment by XyloDrone** [comment]
![Kodadot_Logo+Slogan](https://user-images.githubusercontent.com/84407059/143869423-22183ef3-58dd-4ac5-8af1-b3c303816435.png)

**Comment by yangwao** [comment]
in #18

**Comment by XyloDrone** [comment]
Koda Outline Logo 
![Asset 10@4x](https://user-images.githubusercontent.com/84407059/146208608-87652442-95bc-4d97-802f-7ea7b3cef2b9.png)

KodaDot Outline Logo 
![Asset 2@4x](https://user-images.githubusercontent.com/84407059/146209809-2048b304-2171-4648-87b8-d397e5f0ea53.png)

K Outline Logo 
![Asset 3@4x](https://user-images.githubusercontent.com/84407059/146210572-61cacb34-d6e0-4215-b72d-0c813faac947.png)

K Graphic Logo 
![K_graphic logo](https://user-images.githubusercontent.com/84407059/146210655-bca2700e-c108-4665-8c0b-98dee4ccae12.png)


[KodaDot_Logo Pack 1_SVG.zip](https://github.com/kodadot/kodadot-presskit/files/7720484/KodaDot_Logo.Pack.1_SVG.zip)
[KodaDot_Logo set 2.zip](https://github.com/kodadot/kodadot-presskit/files/7720487/KodaDot_Logo.set.2.zip)

**Comment by yangwao** [comment]
yeah closing commitet https://tenor.com/view/obi-wan-kenobi-of-course-i-know-him-hes-me-gif-12774102
