### ISSUE TITLE
Export all needed KodaDot v3 

### ISSUE THREAD

**Issue by yangwao** [kodadot/kodadot-presskit#17]
Let's export all needed stuff for PR materials like branding etc for others @XyloDrone 

###  we need it for 
- new web page update https://github.com/kodadot/nft-gallery/issues/1207
- kodaforest documentary
- stickers
- logo contest
- what's coming next like media announcement etc
- for upcoming airdrops, nft artists etc

**Comment by yangwao** [comment]
@XyloDrone let's prepare exports I can push it there, got really demand and for some people Figma crashes and it's pain 😄

**Comment by XyloDrone** [comment]
Webpage Logo:
![KODA (1)](https://user-images.githubusercontent.com/84407059/143863153-034b80b6-62cb-420e-85eb-2d8a75c3201b.png)

**Comment by XyloDrone** [comment]
Previous stickers
![KoadDot Sticker](https://user-images.githubusercontent.com/84407059/143864528-86624825-22e3-442f-8bac-47ca435ed8a6.png)

Let me know if I should make stickers with new logo.

**Comment by XyloDrone** [comment]
[Link to logo competition](https://github.com/kodadot/weyland/issues/9)

**Comment by XyloDrone** [comment]
KodaDot rebranding article ready to relese: https://hackmd.io/_yNBBeu5T-S5qHkqX0lOpw
Just need to confirm our current no of users or remove this + decide which platform to post on.

**Comment by XyloDrone** [comment]
Next article: Gig Economy

**Comment by XyloDrone** [comment]
All PNG exports for documentary are in #16 .

**Comment by yangwao** [comment]
@XyloDrone let's add these rest here and I can push them there :) 

![telegram-cloud-photo-size-4-5895439541655943060-y](https://user-images.githubusercontent.com/5887929/146189452-4eac554a-bb59-450e-b21f-599876a3ecfe.jpg)

**Comment by yangwao** [comment]
We need squaare exports as well for kodadot where canvas is squarish or some 16:10 afaik

**Comment by XyloDrone** [comment]
Square exports
![Koda_BLK+slogan](https://user-images.githubusercontent.com/84407059/146215162-a8e1509e-83c9-4a6a-9087-5c84ad597921.png)

![Koda_pink+slogan](https://user-images.githubusercontent.com/84407059/146215156-17730228-a607-4c5d-858a-e7d33cb8b69a.png)
![Koda_wht+slogan](https://user-images.githubusercontent.com/84407059/146215157-443f7533-fff9-4283-b96a-b82914e72a08.png)
![Koda_Pink](https://user-images.githubusercontent.com/84407059/146215127-9afc4bf9-aa41-4a63-9a26-fdb7feff2134.png)
![Koda_Wht](https://user-images.githubusercontent.com/84407059/146215148-3f5e8057-686a-4f38-bde4-a3acc238195c.png)
![Koda_Blk](https://user-images.githubusercontent.com/84407059/146215152-eeccdc40-5579-4aa0-92a4-c78dfa1d887d.png)

**Comment by XyloDrone** [comment]
Guides can be found here: https://www.figma.com/file/XEiqGUitNgIFE0AIgA6XAx/?node-id=0%3A1
