### ISSUE TITLE
Need new card for Discord server invite

### ISSUE THREAD

**Issue by yangwao** [kodadot/kodadot-presskit#19]
https://support.discord.com/hc/en-us/articles/360028716472

![image](https://user-images.githubusercontent.com/5887929/145713092-08497c49-49a6-47b4-84f6-18e06563127b.png)

**Comment by XyloDrone** [comment]
Server 
![Server image](https://user-images.githubusercontent.com/84407059/145789846-1622fd66-3b0e-4f64-a8ce-5abf9be1d8a9.png)

V3 invite + logo ( I belive this was already linked somewhere, can't seem to find it) 

![Discord invite](https://user-images.githubusercontent.com/84407059/145790967-186648ee-f159-4f7c-833e-cb6512d0da1a.png)

V3 invite + text 
![KodaDot Discord](https://user-images.githubusercontent.com/84407059/145791033-e2f75af1-399e-497a-9d60-7f7dac849db9.png)

**Comment by yangwao** [comment]
Used very last one! 

Let's test and we can change it later if not fit 
![image](https://user-images.githubusercontent.com/5887929/147356721-595dce23-0251-4ed8-9b87-4a8a01963500.png)
